version: '3'
services:
  ntpsec:
    build: .
    image: publicarray/ntpsec
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.3'
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "123:123"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
